development:
  adapter: sqlite3
  database: db/development.sqlite3

production:
  adapter: mysql2
  reconnect: true
  host:     <%= ENV['MYSQL_PORT_3306_TCP_ADDR'] %>
  database: <%= ENV['MYSQL_ENV_MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_ENV_MYSQL_USER'] %>
  password: <%= ENV['MYSQL_ENV_MYSQL_PASSWORD'] %>
